// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI7j8rCNHjLY8g-EDZTY1aZp56P4BJOEI',
    appId: '1:1060591687534:web:569b8e99432f41efdad37f',
    messagingSenderId: '1060591687534',
    projectId: 'road-accident-system-dit',
    authDomain: 'road-accident-system-dit.firebaseapp.com',
    storageBucket: 'road-accident-system-dit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRbAtDo40FWziCreIOpBwa3RRZCDUEp1U',
    appId: '1:1060591687534:android:cf2b1f1a1631049adad37f',
    messagingSenderId: '1060591687534',
    projectId: 'road-accident-system-dit',
    storageBucket: 'road-accident-system-dit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZMOVzixlInrC4WMCw8kkpA1hxdS02NOQ',
    appId: '1:1060591687534:ios:56e2bd6f0cd1097ddad37f',
    messagingSenderId: '1060591687534',
    projectId: 'road-accident-system-dit',
    storageBucket: 'road-accident-system-dit.firebasestorage.app',
    iosBundleId: 'com.example.roadAccidentSystem',
  );
}
